In [3]:
import pandas as pd
from sqlalchemy import create_engine
from pandas.io import sql

# Database creds, don't share on public repo
hostname='95.217.156.58'
dbname='crimeStats'
uname='sandwich'
pwd='321#@!IdiotSandwich'
engine = create_engine("mysql+pymysql://{user}:{pw}@{host}/{db}".format(host=hostname, db=dbname, user=uname, pw=pwd))

In [5]:
# get database as df
df = pd.read_sql('SELECT * FROM crimeTable', con=engine)

<hr>
<hr><hr><hr><hr><hr><hr>

### ------------------------------------------------

In [40]:
# get database as df
dfr = pd.read_sql('SELECT * FROM crimeTableRaw', con=engine)

In [41]:
dfr

,index,arrest_key,arrest_date,pd_cd,pd_desc,ky_cd,ofns_desc,law_code,law_cat_cd,arrest_boro,...,perp_race,x_coord_cd,y_coord_cd,latitude,longitude,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih
0,0,32311380,2007-06-18T00:00:00.000,511.0,"CONTROLLED SUBSTANCE, POSSESSION 7",235.0,DANGEROUS DRUGS,PL 2200300,M,Q,...,BLACK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,192799737,2019-01-26T00:00:00.000,177.0,SEXUAL ABUSE,116.0,SEX CRIMES,PL 1306503,F,M,...,BLACK,1000555.0,230994.0,40.800694,-73.941109,13093.0,7.0,4.0,36.0,16.0
2,2,193260691,2019-02-06T00:00:00.000,NaN,None,NaN,None,PL 2203400,F,M,...,UNKNOWN,986685.0,215375.0,40.757839,-73.991212,13094.0,12.0,4.0,10.0,8.0
3,3,149117452,2016-01-06T00:00:00.000,153.0,RAPE 3,104.0,RAPE,PL 1302503,F,K,...,BLACK,998032.0,175598.0,40.648650,-73.950336,13510.0,61.0,2.0,11.0,40.0
4,4,190049060,2018-11-15T00:00:00.000,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,K,...,BLACK,1003606.0,185050.0,40.674583,-73.930222,17615.0,16.0,2.0,49.0,49.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5011995,995,24079154,2006-08-29T00:00:00.000,567.0,"MARIJUANA, POSSESSION 4 & 5",235.0,DANGEROUS DRUGS,PL 2211001,M,B,...,BLACK,1008856.0,250062.0,40.853011,-73.911057,10931.0,6.0,5.0,29.0,29.0
5011996,996,24142966,2006-09-04T00:00:00.000,490.0,"STOLEN PROPERTY 3,POSSESSION",232.0,POSSESSION OF STOLEN PROPERTY 5,PL 1654000,M,B,...,BLACK,1027935.0,238389.0,40.820899,-73.842167,11611.0,58.0,5.0,31.0,26.0
5011997,997,24288752,2006-09-13T00:00:00.000,567.0,"MARIJUANA, POSSESSION 4 & 5",235.0,DANGEROUS DRUGS,PL 2211001,M,M,...,BLACK HISPANIC,1000038.0,243153.0,40.834068,-73.942948,13090.0,47.0,4.0,23.0,21.0
5011998,998,24435034,2006-09-22T00:00:00.000,639.0,AGGRAVATED HARASSMENT 2,361.0,OFF. AGNST PUB ORD SENSBLTY & RGHTS TO PRIV,PL 2403002,M,B,...,WHITE HISPANIC,1027440.0,251415.0,40.856654,-73.843872,11270.0,59.0,5.0,12.0,32.0
5011999,999,24304727,2006-09-14T00:00:00.000,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1201001,F,K,...,WHITE HISPANIC,987309.0,190698.0,40.690106,-73.988971,16865.0,68.0,2.0,38.0,54.0

In [45]:
len(pd.unique(dfr['arrest_key']))

3882402

In [47]:
df=dfr.drop_duplicates(subset=['arrest_key'])

In [56]:
df['age_group']

0          18-24
1          45-64
2          25-44
3          25-44
4          25-44
           ...
5011903      <18
5011904      <18
5011905    18-24
5011906    25-44
5011907    45-64
Name: age_group, Length: 3882402, dtype: object

In [64]:
# what is the other group 
df.groupby('age_group')['age_group'].count().nlargest(10)

age_group
25-44    1793829
18-24    1020459
45-64     715914
<18       319636
65+        32416
895           12
894            6
945            6
928            5
935            5
Name: age_group, dtype: int64